# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HarryMalik12/FlyRank_Internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

# 1. My Lane as an ML Task

### Lane

Refresh / Content Opportunity Scoring

### ML Task Type

Ranking / Scoring

### Why

The goal is not simply to classify pages as good or bad. Instead, we want to rank content pages by priority so content teams know which pages should be refreshed first. Every page receives a priority score, allowing the team to focus on the pages with the greatest opportunity for improvement.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

# 2. Target or Proxy

The starter dataset does not directly provide a "refresh priority" column.

Instead, I will use the observed trend of a page as a proxy.

Pages with declining search performance represent stronger candidates for content refresh, while stable or growing pages have lower refresh priority.

The long-term goal is to build a model that assigns every page a refresh opportunity score.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

# 3. Success Metric

Since this project is designed as a ranking problem, success is measured by how well the model prioritizes pages that genuinely need attention.

A useful ranking should place declining pages higher than stable or improving pages so content editors can spend their time on the most valuable opportunities.

The final evaluation will compare the ranking produced by the machine learning model against a simple rule-based baseline.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [3]:
!git clone https://github.com/HarryMalik12/FlyRank_Internship.git

import os
import pandas as pd

dataset_path = "/content/FlyRank_Internship/data/raw/content_refresh_anonymized.csv"

print("Dataset exists:", os.path.exists(dataset_path))

df = pd.read_csv(dataset_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Cloning into 'FlyRank_Internship'...
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 128 (delta 40), reused 86 (delta 20), pack-reused 0 (from 0)
Receiving objects: 100% (128/128), 1.84 MiB | 15.10 MiB/s, done.
Resolving deltas: 100% (40/40), done.
Dataset exists: True
Dataset loaded successfully!
Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [4]:
import pandas as pd

df = pd.read_csv("/content/FlyRank_Internship/data/raw/content_refresh_anonymized.csv")

print("Shape:", df.shape)

df.head()

Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [5]:
columns = [
    "content_id",
    "client_id",
    "content_type",
    "ctr",
    "avg_position",
    "engagement_rate",
    "trend_direction"
]

df[columns].head(10)

,content_id,client_id,content_type,ctr,avg_position,engagement_rate,trend_direction
0,content_304f48230142,client_f369cb89fc,keyword article,0.76,10.6,5.88,down
1,content_a1fb4e703a9e,client_4e07408562,keyword article,0.05,20.3,0.00,down
2,content_9aa793d4d895,client_7f2253d7e2,keyword article,0.09,36.5,0.00,down
3,content_331d6c4de07b,client_19581e27de,keyword article,0.49,6.2,1.28,stable
4,content_d99b7a2d90ca,client_3fdba35f04,keyword article,0.13,44.0,0.00,down
5,content_d4084a4bc775,client_f369cb89fc,keyword article,0.03,8.5,0.00,down
6,content_9a34b442b552,client_8722616204,keyword article,0.00,7.0,0.00,down
7,content_a63219c6e95a,client_19581e27de,keyword article,0.06,21.2,3.57,stable
8,content_5e6c160719bc,client_6208ef0f77,keyword article,0.09,46.0,5.88,down
9,content_c27558df2b0c,client_19581e27de,keyword article,0.16,4.9,0.00,down

## Unit of Analysis

Each row represents one content page.

For every content page, the dataset contains search performance, engagement metrics, and content characteristics. The model will assign a refresh opportunity score to each page based on these observed features.

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

# 5. Why ML Beats a Fixed Rule

A simple rule such as "refresh every page with CTR below 1%" ignores many other important signals.

Machine learning can consider multiple features simultaneously, including click-through rate, average position, engagement rate, search volume, and content characteristics.

By learning patterns across many pages, a machine learning model can produce more useful rankings than a single fixed threshold.

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.